### ISSUE TITLE
Migrate code:arguments support

### ISSUE THREAD

**Issue by tpluscode** [zazuko/rdf-native-loader-code#2]
Currently we support `code:arguments` using custom code only in barnard59-core.

The work done in zazuko/barnard59-core#39 should be migrated to this repo.

---

Now, the arguments cannot be a loader like `code:EcmaScript` because we only rely on `rdf:type` to select the loader.

Hence, I propose an explicit usage, where the arguments would be a helper module. Here's an example loader, which gets the arguments from `code:arguments` property.

```js
const loadArguments = require('rdf-native-loader-code/arguments')
cons cf = require('clownface')

module.exports = (term, dataset, { context, loaderRegistry }) => {
  return parseArguments(cf(dataset).node(term).out(ns.code.arguments), context, loaderRegistry)
}
```

Note that any predicate could be used thus giving the implementor a degree of flexibility.

**Comment by tpluscode** [comment]
@bergos @vhf thoughts?

**Comment by bergos** [comment]
I see it even as part of the concept of the loaders to provide the loader function separate from the type/datatype. Like you said, it gives some degree of flexibility. I used it already in the example of the [Python RDF Loader](https://github.com/bergos/py-rdf-native-loader/blob/master/example.py#L7). It's only important that we use the loader interface on all levels, if some kind of nested loading is done, so each level can be reused. This gives two options how to use the loaders:

- register the loader to a custom type/datatype
- directly call the loader function without the registry
